FormKey: 06347C:SexLab.esm
EditorID: SexLabConfigMenu
FormVersion: 43
VirtualMachineAdapter:
  Scripts:
  - Name: sslConfigMenu
    Properties:
    - MutagenObjectType: ScriptObjectProperty
      Name: AudioSFX
      Object: 061428:SexLab.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: AudioVoice
      Object: 061429:SexLab.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: CalypsStrapon
      Object: 01A22A:SexLab.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: CleanSystemFinish
      Object: 06CB9E:SexLab.esm
    - MutagenObjectType: ScriptStringProperty
      Name: modname
      Data: SexLab
    - MutagenObjectType: ScriptObjectProperty
      Name: NoSKSE
      Object: 06CB9C:SexLab.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: OldSKSE
      Object: 06CB9B:SexLab.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: OldSkyrim
      Object: 06CB9D:SexLab.esm
    - MutagenObjectType: ScriptObjectProperty
      Name: PlayerRef
      Object: 000014:Skyrim.esm
  FileName: ''
  Aliases:
  - Property:
      Name: ''
      Object: 06347C:SexLab.esm
      Alias: 0
    Scripts:
    - Name: SKI_PlayerLoadGameAlias
Name:
  TargetLanguage: English
  Value: SexLab MCM
Flags:
- StartGameEnabled
- 0x10
Priority: 70
QuestFormVersion: 32
Filter: SexLab\
NextAliasID: 1
Aliases:
- Name: PlayerAlias
  Flags: []
  ForcedReference: 000014:Skyrim.esm
  VoiceTypes: Null
